# SPDX-License-Identifier: MIT
# Replace exactly one pinned source; leave the encoder and all other sources.
function(p4desk_jpeg_full_range_replace_source target original generated)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "JPEG full-range patch cannot find target ${target}")
    endif()
    if(NOT EXISTS "${generated}")
        message(FATAL_ERROR "JPEG full-range generated source does not exist: ${generated}")
    endif()
    get_filename_component(original_abs "${original}" ABSOLUTE)
    get_filename_component(generated_name "${generated}" NAME)
    if(NOT generated_name STREQUAL "jpeg_decode.c")
        message(FATAL_ERROR "JPEG full-range patch must retain the original basename")
    endif()
    get_target_property(source_dir "${target}" SOURCE_DIR)
    get_target_property(sources "${target}" SOURCES)
    set(remaining "")
    set(matched 0)
    foreach(source IN LISTS sources)
        get_filename_component(source_abs "${source}" ABSOLUTE BASE_DIR "${source_dir}")
        if(source_abs STREQUAL original_abs)
            math(EXPR matched "${matched} + 1")
        else()
            list(APPEND remaining "${source}")
        endif()
    endforeach()
    if(NOT matched EQUAL 1)
        message(FATAL_ERROR "JPEG full-range patch expected one original decoder source; found ${matched}")
    endif()

    set_property(TARGET "${target}" PROPERTY SOURCES "${remaining}")
    target_sources("${target}" PRIVATE "${generated}")
    # jpeg_private.h and private/jpeg_parse_marker.h remain in the SDK component.
    get_filename_component(original_dir "${original_abs}" DIRECTORY)
    target_include_directories("${target}" PRIVATE "${original_dir}")
    set_source_files_properties("${generated}" PROPERTIES GENERATED TRUE)
    set_property(TARGET "${target}" PROPERTY P4DESK_JPEG_FULL_RANGE_PATCH "${generated}")
endfunction()

function(p4desk_jpeg_full_range_finish)
    get_property(original GLOBAL PROPERTY P4DESK_JPEG_FULL_RANGE_ORIGINAL)
    get_property(generated GLOBAL PROPERTY P4DESK_JPEG_FULL_RANGE_GENERATED)
    p4desk_jpeg_full_range_replace_source(__idf_esp_driver_jpeg "${original}" "${generated}")
endfunction()
