# Replace exactly one pinned SDK source, preserving all other target sources.
function(p4desk_lcd_observer_replace_source target original generated header_dir)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "DPI observer cannot find target ${target}")
    endif()
    if(NOT EXISTS "${generated}")
        message(FATAL_ERROR "DPI observer generated source does not exist: ${generated}")
    endif()
    get_filename_component(original_abs "${original}" ABSOLUTE)
    get_target_property(source_dir "${target}" SOURCE_DIR)
    get_target_property(sources "${target}" SOURCES)
    set(remaining "")
    set(matched 0)
    foreach(source IN LISTS sources)
        get_filename_component(source_abs "${source}" ABSOLUTE BASE_DIR "${source_dir}")
        if(source_abs STREQUAL original_abs)
            math(EXPR matched "${matched} + 1")
        else()
            list(APPEND remaining "${source}")
        endif()
    endforeach()
    if(NOT matched EQUAL 1)
        message(FATAL_ERROR "DPI observer expected one original DPI source; found ${matched}")
    endif()

    set_property(TARGET "${target}" PROPERTY SOURCES "${remaining}")
    target_sources("${target}" PRIVATE "${generated}")
    # The generated file keeps the original basename for esp_lcd/linker.lf's
    # esp_lcd_panel_dpi ISR rules. The original sibling private header is needed.
    get_filename_component(original_dir "${original_abs}" DIRECTORY)
    target_include_directories("${target}" PRIVATE "${original_dir}" "${header_dir}")
    set_source_files_properties("${generated}" PROPERTIES GENERATED TRUE)
    set_property(TARGET "${target}" PROPERTY P4DESK_LCD_FRAME_OBSERVER_PATCH "${generated}")
endfunction()

function(p4desk_lcd_observer_finish)
    get_property(original GLOBAL PROPERTY P4DESK_DPI_OBSERVER_ORIGINAL)
    get_property(generated GLOBAL PROPERTY P4DESK_DPI_OBSERVER_GENERATED)
    get_property(header_dir GLOBAL PROPERTY P4DESK_DPI_OBSERVER_INCLUDE)
    p4desk_lcd_observer_replace_source(__idf_esp_lcd "${original}" "${generated}" "${header_dir}")
endfunction()
