#!/usr/bin/env python3
"""Compile light tile variants of P4Desk's original Folio SVGs (MIT)."""
import argparse,hashlib,importlib.util,json,subprocess
from pathlib import Path
import xml.etree.ElementTree as E
ROOT=Path(__file__).resolve().parents[1]
PALETTE={'clock':'d0e2e8','timer':'f3d9d0','notes':'f4e4bd','calculator':'d3e9df','mac':'d9e4f4','settings':'dde7eb','display':'d1eaeb','screen':'e4dcef','file-manager':'e4ddf0','office-viewer':'f1dce6','sub2api-monitor':'cde9e2'}
def main():
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    spec=importlib.util.spec_from_file_location('icons',ROOT/'scripts/generate-vector-icons.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
    E.register_namespace('','http://www.w3.org/2000/svg')
    parts=['// Original P4Desk Folio light variants. MIT; generated by scripts/generate-folio-light-icons.py.\n','use super::{Color, VectorCommand, VectorIcon, VectorLayer, VectorPaint, VectorShape};\nuse crate::tiny_gfx::{FillRule, LineCap, LineJoin};\n'];entries=[]
    for name,base in PALETTE.items():
        source=ROOT/'assets/app_icons/source'/(name+'.svg');root=E.fromstring(source.read_bytes())
        disk=next(e for e in root if e.tag.endswith('}circle') and e.get('r')=='56')
        disk.set('fill','#'+base)
        dest=ROOT/'assets/app_icons/light'/(name+'.svg');E.indent(root);data=E.tostring(root,encoding='utf-8',xml_declaration=True)+b'\n'
        if args.check:assert dest.read_bytes()==data,str(dest)
        else:dest.parent.mkdir(exist_ok=True);dest.write_bytes(data)
        symbol='FOLIO_LIGHT_'+name.upper().replace('-','_');compiled,layers=m.compile_svg(dest,symbol);parts.append(compiled)
        entries.append({'id':name,'source_sha256':hashlib.sha256(source.read_bytes()).hexdigest(),'base_color':base,'layers':layers})
    rust=subprocess.run(['rustfmt','--edition','2021','--emit','stdout'],input=''.join(parts),text=True,capture_output=True,check=True).stdout.encode()
    for path,data in [('crates/tiny-flutter/src/graphics/folio_light_icons_generated.rs',rust),('assets/folio-light-icons.json',(json.dumps({'license':'MIT','icons':entries},indent=2)+'\n').encode())]:
        dest=ROOT/path
        if args.check:assert dest.read_bytes()==data,str(dest)
        else:dest.write_bytes(data)
    print(json.dumps({'icons':len(entries),'valid':True,'mode':'check' if args.check else 'generate'}))
if __name__=='__main__':main()
