// Generate small native DINish Heavy tabular outlines. Font glyphs remain OFL-1.1.
// Firmware embeds vector commands; no font parser, bitmap scaling or font cache.
import Foundation
import CoreText
import CoreGraphics
import CryptoKit

func fail(_ message: String) -> Never {
    FileHandle.standardError.write(Data((message + "\n").utf8)); exit(1)
}
let root = URL(fileURLWithPath: #filePath).deletingLastPathComponent().deletingLastPathComponent()
let source = root.appendingPathComponent("assets/fonts/source/DINish-Heavy.ttf")
let output = root.appendingPathComponent("apps/app-launcher/src/battery_digits_generated.rs")
let expected = "6812edbc60553218229b256670b57fdaf8186969e56f9aa7c19bcb19c66ad263"
let digest = SHA256.hash(data: try Data(contentsOf: source)).map { String(format: "%02x", $0) }.joined()
guard digest == expected else { fail("Pinned DINish Heavy source does not match.") }
guard let descriptors = CTFontManagerCreateFontDescriptorsFromURL(source as CFURL) as? [CTFontDescriptor],
      let original = descriptors.first else { fail("Cannot load font.") }
let settings: [[String: Any]] = [
    [kCTFontFeatureTypeIdentifierKey as String: 6, kCTFontFeatureSelectorIdentifierKey as String: 0],
    [kCTFontFeatureTypeIdentifierKey as String: 21, kCTFontFeatureSelectorIdentifierKey as String: 1],
]
let descriptor = CTFontDescriptorCreateCopyWithAttributes(original,
    [kCTFontFeatureSettingsAttribute as String: settings] as CFDictionary)
let font = CTFontCreateWithFontDescriptor(descriptor, 1000, nil)
let chars = Array("0123456789-")
let paths: [CGPath] = chars.map { ch in
    let text = NSAttributedString(string: String(ch), attributes: [.init(kCTFontAttributeName as String): font])
    let runs = CTLineGetGlyphRuns(CTLineCreateWithAttributedString(text)) as! [CTRun]
    guard runs.count == 1, CTRunGetGlyphCount(runs[0]) == 1 else { fail("Unexpected fallback.") }
    var glyph: CGGlyph = 0
    CTRunGetGlyphs(runs[0], CFRange(location: 0, length: 1), &glyph)
    guard let path = CTFontCreatePathForGlyph(font, glyph, nil) else { fail("Missing outline.") }
    return path
}
let scale = min(16 / paths.map { $0.boundingBoxOfPath.width }.max()!,
                24 / paths.map { $0.boundingBoxOfPath.height }.max()!)
func number(_ value: CGFloat) -> String {
    var s = String(format: "%.5f", locale: Locale(identifier: "en_US_POSIX"), Double(value))
    while s.last == "0" { s.removeLast() }
    if s.last == "." { s += "0" }
    return s
}
var rust = """
// Generated by scripts/generate-battery-vectors.swift. Do not edit by hand.
// DINish Heavy glyph outlines: SIL OFL-1.1; third_party/licenses/DINish-OFL.txt.
// Source SHA256: \(expected). Original outlines, uniform scale, optical centering.
use tiny_flutter::graphics::{VectorCommand, VectorIcon, VectorLayer, VectorPaint, VectorShape};
use tiny_flutter::tiny_gfx::{FillRule, LineCap, LineJoin};
pub static DIGITS: [VectorIcon; 11] = [

"""
for path in paths {
    let bounds = path.boundingBoxOfPath
    func p(_ pt: CGPoint) -> String {
        let x = 9 + (pt.x - bounds.midX) * scale
        let y = 13 - (pt.y - bounds.midY) * scale
        return "\(number(x)),\(number(y))"
    }
    var commands: [String] = []
    path.applyWithBlock { ptr in
        let e = ptr.pointee
        switch e.type {
        case .moveToPoint: commands.append("VectorCommand::Move(\(p(e.points[0])))")
        case .addLineToPoint: commands.append("VectorCommand::Line(\(p(e.points[0])))")
        case .addQuadCurveToPoint: commands.append("VectorCommand::Quad(\(p(e.points[0])),\(p(e.points[1])))")
        case .addCurveToPoint: commands.append("VectorCommand::Cubic(\(p(e.points[0])),\(p(e.points[1])),\(p(e.points[2])))")
        case .closeSubpath: commands.append("VectorCommand::Close")
        @unknown default: fail("Unsupported path element.")
        }
    }
    rust += "VectorIcon { width:18.0,height:26.0,layers:&[VectorLayer {shape:VectorShape::Path(&[\(commands.joined(separator: ","))]),fill:Some(VectorPaint::Tint(1.0)),stroke:None,stroke_width:0.0,line_cap:LineCap::Round,line_join:LineJoin::Round,fill_rule:FillRule::Winding}]},\n"
}
rust += "];\n"
let formatter = Process(); formatter.executableURL = URL(fileURLWithPath: "/usr/bin/env")
formatter.arguments = ["rustfmt", "--edition", "2021", "--emit", "stdout"]
let input = Pipe(), formatted = Pipe()
formatter.standardInput = input; formatter.standardOutput = formatted
try formatter.run()
input.fileHandleForWriting.write(Data(rust.utf8)); try input.fileHandleForWriting.close()
let result = formatted.fileHandleForReading.readDataToEndOfFile(); formatter.waitUntilExit()
guard formatter.terminationStatus == 0 else { fail("rustfmt failed.") }
if CommandLine.arguments.contains("--check") {
    guard result == (try Data(contentsOf: output)) else { fail("Battery vectors need regeneration.") }
} else { try result.write(to: output) }
print("Battery glyphs: 11 original DINish Heavy outlines, \(result.count) source bytes; verified.")
